---
output: github_document
bibliography: references.bib
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "README-"
)
# Please put your title here to include it in the file below.
Title <- "External Cues and Policy Preferences: Rethinking the Drivers of Policy Positions"
Authors <- "Francisca Castro, Jennifer Oser, Fernando Feitosa & Nir Ginberg"
Year <- "2024"
```

# `r Title`

[Francisca Castro](https://francisca-castro.com/) • Institute of Social Sciences • Humboldt-Universität zu Berlin\
[Jennifer Oser](https://www.jenniferoser.com/) • Department of Politics and Government • Ben-Gurion University of the Negev\
[Fernando Feitosa](https://ferfeitosa.github.io/) • Department of Political Science • McGill University\
[Nir Grinberg](https://www.nirg.net/) • Department of Software and Information Systems Engineering • Ben-Gurion University of the Negev

------------------------------------------------------------------------

## Abstract

At a time when the influence of multiple types of external cues on opinion formation is gaining attention due to their relevance for preference formation, this research note investigates how external cues from political elites and close friends shape individual policy preferences. Building on prior studies byBarber and Pope (2019, 2024) regarding Donald Trump's impact on people's policy preferences in surveys fielded during his 2017-2021 presidency, we examine whether this influence persists soon after Trump's first presidential tenure concludes in late 2021 through a survey experiment to a representative sample of Americans. We also assess the influence of a second external cue that has gained attention due to the growing role of social media in political processes: a close friend, who might also serve as a relevant figure for policy position formation. We find that the effects of these cues are limited and conditional on respondents' characteristics, such as Republican party affiliation and low levels of political knowledge. These findings suggest the importance of official office-holding for the influence of political elites, and also indicate that policy preferences may be less malleable through social networks than is often presumed in contemporary discourse.

------------------------------------------------------------------------

## How to download and replicate

You can download the data for replication [here](https://github.com/frcastrog/erc-paper-policy-preferences/blob/main/CCES21_BGU_OUTPUT.sav). This is the raw data of Cooperative Election Study (CES) for the period November and December 2021.

The script `00-data-prep` contains the code to make the necessary modifications to the original data, which includes recoding, flag creation, and cleanup.

The script `01-replication` contains the code to replicate the figures and tables of both the manuscript and the supplementary information.

## References
